/*
 * To change this template, choose Tools | Templates and open the template in the editor.
 */
package com.quvizo.ui.misc;

import java.util.Date;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import com.quvizo.data.entity.Presentation;
import com.quvizo.universal.EntityOverlord;
import com.quvizo.universal.UI;

/**
 *
 * @author peki
 */
public class NewPresentationDialog extends javax.swing.JDialog
{

    /**
     * Creates new form NewPresentationDialog
     */
    public NewPresentationDialog(java.awt.Frame parent)
    {
	super(parent, true);
	initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/media/logo.png")).getImage());
	this.getRootPane().setDefaultButton(okbtn);
	this.setAlwaysOnTop(true);
	this.namebox.requestFocusInWindow();
	this.requestFocus();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namebox = new javax.swing.JTextField();
        okbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Presentation");

        namebox.setToolTipText("New Presentation name");

        okbtn.setText("Ok");
        okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbtnActionPerformed(evt);
            }
        });

        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        jLabel1.setText("New Presentation:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 190, Short.MAX_VALUE)
                        .addComponent(okbtn)
                        .addGap(18, 18, 18)
                        .addComponent(cancelbtn))
                    .addComponent(namebox)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(namebox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okbtn)
                    .addComponent(cancelbtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelbtnActionPerformed
    {//GEN-HEADEREND:event_cancelbtnActionPerformed
	this.setVisible(false);
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void okbtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okbtnActionPerformed
    {//GEN-HEADEREND:event_okbtnActionPerformed
	createPresentation();
    }//GEN-LAST:event_okbtnActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField namebox;
    private javax.swing.JButton okbtn;
    // End of variables declaration//GEN-END:variables

    private void createPresentation()
    {
	if (namebox.getText().isEmpty())
	{

	    JOptionPane.showMessageDialog(null, "Can't create a PResentation without a name.");
	    return;
	}

	EntityManager em = EntityOverlord.getInstance().getEm();

	Presentation newPres = new Presentation();
	newPres.setName(namebox.getText());
	newPres.setAddedOn(new Date());
	newPres.setUpdatedOn(new Date());

	em.getTransaction().begin();
	em.persist(newPres);
	em.getTransaction().commit();

	System.out.println(newPres.getId());

	UI.selectedPresentation = newPres;

	this.setVisible(false);
    }
}
