/*
 * To change this template, choose Tools | Templates and open the template in the editor.
 */
package com.quvizo.ui.misc;

/**
 *
 * @author peki
 */
public class TextDialog extends javax.swing.JDialog
{

    /**
     * Creates new form NewPresentationDialog
     */
    public TextDialog(java.awt.Frame parent)
    {
	super(parent, true);
	initComponents();
	this.getRootPane().setDefaultButton(okbtn);
	this.setAlwaysOnTop(true);
	this.textbox.requestFocusInWindow();
	this.requestFocus();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        bodyLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textbox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Presentation");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        okbtn.setText("Ok");
        okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbtnActionPerformed(evt);
            }
        });

        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        bodyLabel.setText("New Presentation:");

        textbox.setColumns(20);
        textbox.setRows(3);
        jScrollPane1.setViewportView(textbox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okbtn)
                        .addGap(18, 18, 18)
                        .addComponent(cancelbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bodyLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bodyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okbtn)
                    .addComponent(cancelbtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelbtnActionPerformed
    {//GEN-HEADEREND:event_cancelbtnActionPerformed
	result = null;
	this.setVisible(false);
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void okbtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okbtnActionPerformed
    {//GEN-HEADEREND:event_okbtnActionPerformed
	result = textbox.getText();
	this.setVisible(false);
    }//GEN-LAST:event_okbtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
	// TODO add your handling code here
	textbox.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bodyLabel;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okbtn;
    private javax.swing.JTextArea textbox;
    // End of variables declaration//GEN-END:variables
    String result;
    
    public String showTextInput(String title, String info, String initial)
    {
	setTitle(title);
	bodyLabel.setText(info);
	
	if(initial==null)
	    initial="";
	
	textbox.setText(initial);
	this.setVisible(true);
	
	return result;
    }
}
