/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quvizo.ui.importer;

import java.awt.Desktop;
import java.util.ArrayList;
import javax.swing.SwingUtilities;

/**
 *
 * @author peki
 */
public class ResultDialog extends javax.swing.JDialog
{
    
    /**
     * Creates new form ImportResultDialog
     */
    public ResultDialog(java.awt.Frame parent, boolean modal,ArrayList<String> fails, String text)
    {
        super(parent, modal);
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/media/logo.png")).getImage());
        this.setLocationRelativeTo(null);
        initComponents();
        msglabel.setText(text);
        if(fails!=null && fails.size()>0)
        {
            //errors exist
            StringBuilder sb = new StringBuilder();
            for(String s: fails)
                sb.append(s).append("\n");
                    
            errorField.setText(sb.toString());
        }
        else
            errorpanel.setVisible(false);
        
        this.pack();
    }
    
    public ResultDialog(java.awt.Frame parent, boolean modal,ArrayList<String> fails)
    {
        this(parent,modal,fails,java.util.ResourceBundle.getBundle("i18n/Bundle").getString("import.dialog.finished"));
    }
    
    public static void showMessage(String title, String msg)
    {
        showMessage(title, msg, false, null );
    }
    
    public static void showMessage(final String title, final String msg, final boolean modal,final ArrayList<String> fails)
    {
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                ResultDialog d = new ResultDialog(null,modal,fails,msg);
                d.setTitle(title);
                d.setVisible(true);
            }
        });
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msglabel = new javax.swing.JLabel();
        errorpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        errorField = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i18n/Bundle"); // NOI18N
        setTitle(bundle.getString("import.dialog.ewsays")); // NOI18N
        setAlwaysOnTop(true);

        msglabel.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        msglabel.setText(bundle.getString("import.dialog.processfinished")); // NOI18N

        jLabel2.setText(bundle.getString("import.dialog.errorsencountered")); // NOI18N

        errorField.setEditable(false);
        errorField.setColumns(20);
        errorField.setRows(5);
        jScrollPane1.setViewportView(errorField);

        javax.swing.GroupLayout errorpanelLayout = new javax.swing.GroupLayout(errorpanel);
        errorpanel.setLayout(errorpanelLayout);
        errorpanelLayout.setHorizontalGroup(
            errorpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(errorpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(errorpanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 308, Short.MAX_VALUE)))
                .addContainerGap())
        );
        errorpanelLayout.setVerticalGroup(
            errorpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText(bundle.getString("import.dialog.ok")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(msglabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(msglabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea errorField;
    private javax.swing.JPanel errorpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msglabel;
    // End of variables declaration//GEN-END:variables
}
